<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$_config = $this->helper('Sm\Market\Helper\Data');
?>

<div class="footer-container footer-style-12">
	<div class="footer-wrapper">
        <div class="footer-top">
            <div class="newsletter-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7 col-md-7">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter-title12')->toHtml(); ?>
                        </div>

                        <div class="col-lg-5 col-md-5">
                            <?php echo $block->getChildHtml('form.subscribe.footer'); ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>

		<div class="footer-middle">
            <div class="container">
                <div class="middle-content-top">
                    <div class="row">
                        <div class="col-lg-6 col-md-6">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('description-footer12')->toHtml(); ?>
                        </div>

                        <div class="col-lg-6 col-md-6">
                            <div class="social-content">
                                <div class="title-social"><?php echo __('Follow Us By Socials')?></div>
                                <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Theme::html/social.phtml')->toHtml(); ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="middle-content-bottom">
                    <div class="row">
                        <div class="col-md-3 col-sm-6 col-xs-12 contact-footer">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-footer')->toHtml(); ?>
                        </div>

                        <div class="col-md-3 col-sm-6 col-xs-12 about-store">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about-footer')->toHtml(); ?>
                        </div>

                        <div class="col-md-3 col-sm-6 col-xs-12 customer-services">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('customer-services-footer')->toHtml(); ?>
                        </div>

                        <div class="col-md-3 col-sm-6 col-xs-12 payment-shipping">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-shipping-footer')->toHtml(); ?>
                        </div>
                    </div>
                </div>
            </div>
		</div>

        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 copyright-footer">
                        <?php if($_config->getAdvanced('custom_copyright')){ ?>
                            <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
                        <?php } else {?>
                            <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
                        <?php } ?>
                    </div>

                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 footer-payment">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment-footer-id16')->toHtml(); ?>
                    </div>
                </div>
            </div>
        </div>
	</div>
	
	<?php if($_config->getAdvanced('show_gototop')){ ?>
		<a id="yt-totop-fix" href="javascript:void(0)" title="Go to Top"></a>
	<?php } ?>
</div>




